import { db } from '../index';
import { items } from '../schema';

async function main() {
    const sampleItems = [
        {
            name: 'iPhone 15 Pro',
            description: 'The latest flagship smartphone from Apple featuring titanium design, A17 Pro chip, and advanced camera system',
            category: 'Products',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_zJnvLwcXGHYA6yui-qBOft8dtGWlD8MYvQ&s',
            averageRating: 4.7,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'MacBook Pro M3',
            description: 'Powerful laptop with Apple M3 chip, stunning Liquid Retina XDR display, and all-day battery life',
            category: 'Products',
            imageUrl: 'https://www.indiaistore.com/files/uploads/products/macbook-air-m3/images/hero_small_2x.png?1708555710106',
            averageRating: 4.8,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Sony WH-1000XM5 Headphones',
            description: 'Industry-leading noise canceling wireless headphones with exceptional sound quality and comfort',
            category: 'Products',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYJ12JMPQz_1mdyX406svZd5eun5m9IdSMbA&s',
            averageRating: 4.6,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Samsung Galaxy S24',
            description: 'Flagship Android smartphone with AI features, excellent camera system, and vibrant display',
            category: 'Products',
            imageUrl: 'https://cdn.beebom.com/mobile/samsung-galaxy-s24-plus-front-and-back-2.png',
            averageRating: 4.5,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Grand Canyon',
            description: 'Breathtaking natural wonder featuring massive rock formations and stunning vistas in Arizona',
            category: 'Places',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRW78IjxmOtLNz3f2eD9OwPOklJQvLO_HyTZw&s',
            averageRating: 4.9,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Eiffel Tower',
            description: 'Iconic iron lattice tower in Paris, offering panoramic views of the city',
            category: 'Places',
            imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=400',
            averageRating: 4.8,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Tokyo Disney',
            description: 'Magical theme park combining Disney charm with Japanese hospitality and unique attractions',
            category: 'Places',
            imageUrl: 'https://girleatworld.net/wp-content/uploads/2019/05/tokyo-disneyland-08.jpg',
            averageRating: 4.7,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Central Park NYC',
            description: 'Iconic urban park offering green spaces, walking paths, and cultural attractions in Manhattan',
            category: 'Places',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYFg1fhUSFsOpcW70iE11uXzQuTpfj5tv3fA&s',
            averageRating: 4.6,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Spotify',
            description: 'Leading music streaming service with millions of songs, podcasts, and personalized playlists',
            category: 'Apps',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWh6hfzpYZ_Xl6HXMYj5GDn_nAB0ZzgSTUbQ&s',
            averageRating: 4.5,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Netflix',
            description: 'Popular streaming platform offering movies, TV shows, and original content',
            category: 'Apps',
            imageUrl: 'https://i.pinimg.com/736x/74/1a/3f/741a3f0ffd0804044e73d284fb24e97f.jpg',
            averageRating: 4.4,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'ChatGPT',
            description: 'AI-powered conversational assistant that helps with writing, coding, and problem-solving',
            category: 'Apps',
            imageUrl: 'https://thumbs.dreamstime.com/b/chatgpt-artificial-intelligence-program-logo-openai-company-polygonal-green-background-illustration-banner-news-vector-286505082.jpg',
            averageRating: 4.7,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Notion',
            description: 'All-in-one workspace for notes, tasks, wikis, and databases',
            category: 'Apps',
            imageUrl: 'https://preview.redd.it/what-are-your-thoughts-on-notion-ai-has-it-truly-simplified-v0-2telgdckvbmc1.jpg?width=400&format=pjpg&auto=webp&s=ca8fca67ac9c39e086571875be24b2988cf3af5a',
            averageRating: 4.6,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'The Great Gatsby',
            description: 'Classic American novel by F. Scott Fitzgerald exploring themes of wealth, love, and the American Dream',
            category: 'Books',
            imageUrl: 'https://rukminim2.flixcart.com/image/480/640/l4fxh8w0/book/z/0/y/the-great-gatsby-a-novel-original-imagfbmgfsan3gjg.jpeg?q=90',
            averageRating: 4.3,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: '1984',
            description: 'Dystopian masterpiece by George Orwell about totalitarianism and surveillance',
            category: 'Books',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV4yWihrnwBCaQNXCMF_zSIAPDMidcLtnR3g&s',
            averageRating: 4.7,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Harry Potter and the Sorcerer\'s Stone',
            description: 'Magical adventure story that launched the beloved Harry Potter series by J.K. Rowling',
            category: 'Books',
            imageUrl: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1598823299i/42844155.jpg',
            averageRating: 4.9,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'To Kill a Mockingbird',
            description: 'Pulitzer Prize-winning novel by Harper Lee addressing racial injustice in the American South',
            category: 'Books',
            imageUrl: 'https://m.media-amazon.com/images/I/81gkyAx5-RL._AC_UF1000,1000_QL80_.jpg',
            averageRating: 4.8,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'The Shawshank Redemption',
            description: 'Inspiring drama about hope and friendship in the face of injustice, directed by Frank Darabont',
            category: 'Movies',
            imageUrl: 'https://m.media-amazon.com/images/I/71nBGhNjGIL._AC_UF1000,1000_QL80_.jpg',
            averageRating: 4.9,
            totalReviews: 7,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Inception',
            description: 'Mind-bending sci-fi thriller by Christopher Nolan exploring dreams within dreams',
            category: 'Movies',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXWnBnPN47nWvqWJAxw-vmchKc_2u1zkG6Bw&s',
            averageRating: 4.8,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Interstellar',
            description: 'Epic space exploration film combining stunning visuals with emotional storytelling',
            category: 'Movies',
            imageUrl: 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/8d8f28105415493.619ded067937d.jpg',
            averageRating: 4.7,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'The Dark Knight',
            description: 'Groundbreaking superhero film featuring Heath Ledger\'s iconic Joker performance',
            category: 'Movies',
            imageUrl: 'https://m.media-amazon.com/images/S/pv-target-images/e9a43e647b2ca70e75a3c0af046c4dfdcd712380889779cbdc2c57d94ab63902.jpg',
            averageRating: 4.9,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Blue Hill',
            description: 'Farm-to-table fine dining restaurant in Manhattan featuring seasonal American cuisine',
            category: 'Restaurants',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWFwHWiVfL9ran5W8UbxC4kkFfbD-h2LJx6w&s',
            averageRating: 4.6,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Le Bernardin',
            description: 'Legendary French seafood restaurant with three Michelin stars in New York City',
            category: 'Restaurants',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlwWi_KvMJl5v7dKyf91Vmq8qYraJUk6xgAw&s',
            averageRating: 4.8,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Nobu',
            description: 'Renowned Japanese fusion restaurant known for innovative sushi and elegant atmosphere',
            category: 'Restaurants',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAIxr4yk49_U_wfhpQRPV36DHnL8KJJUtC0A&s',
            averageRating: 4.7,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Per Se',
            description: 'Thomas Keller\'s acclaimed New American restaurant offering exceptional tasting menus',
            category: 'Restaurants',
            imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/4a/56/fa/le-restaurant-perse-a.jpg?w=900&h=500&s=1',
            averageRating: 4.9,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'The Legend of Zelda: Breath of the Wild',
            description: 'Revolutionary open-world adventure game that redefined the Zelda series',
            category: 'Games',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTAFPUkmf9yU3QTAZQECyg-m_PHOAxl6Pjkw&s',
            averageRating: 4.9,
            totalReviews: 7,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Elden Ring',
            description: 'Epic dark fantasy action RPG from FromSoftware with vast open world exploration',
            category: 'Games',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_cg0wulPkBFh1D9b1Q4B3LUgR7zaFdQr08g&s',
            averageRating: 4.7,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'God of War',
            description: 'Critically acclaimed action-adventure following Kratos and Atreus through Norse mythology',
            category: 'Games',
            imageUrl: 'https://m.media-amazon.com/images/M/MV5BMDkxMzExYjAtZmQwMC00MmQzLWE1M2QtMGEwY2M1N2I0NDIwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
            averageRating: 4.8,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Red Dead Redemption 2',
            description: 'Immersive Wild West epic with stunning graphics and compelling narrative',
            category: 'Games',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2PXtURBeowi2QaLDkAXMJ_akB8C8w3DlIgw&s',
            averageRating: 4.8,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(items).values(sampleItems);

    console.log('✅ Items seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});