import { db } from '../index';
import { items } from '../schema';

async function main() {
    const sampleItems = [
        {
            name: 'iPhone 15 Pro',
            description: 'The latest flagship smartphone from Apple featuring titanium design, A17 Pro chip, and advanced camera system',
            category: 'Products',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_zJnvLwcXGHYA6yui-qBOft8dtGWlD8MYvQ&s',
            averageRating: 4.7,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'MacBook Pro M3',
            description: 'Powerful laptop with Apple M3 chip, stunning Liquid Retina XDR display, and all-day battery life',
            category: 'Products',
            imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400',
            averageRating: 4.8,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Sony WH-1000XM5 Headphones',
            description: 'Industry-leading noise canceling wireless headphones with exceptional sound quality and comfort',
            category: 'Products',
            imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400',
            averageRating: 4.6,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Samsung Galaxy S24',
            description: 'Flagship Android smartphone with AI features, excellent camera system, and vibrant display',
            category: 'Products',
            imageUrl: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400',
            averageRating: 4.5,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Grand Canyon',
            description: 'Breathtaking natural wonder featuring massive rock formations and stunning vistas in Arizona',
            category: 'Places',
            imageUrl: 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=400',
            averageRating: 4.9,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Eiffel Tower',
            description: 'Iconic iron lattice tower in Paris, offering panoramic views of the city',
            category: 'Places',
            imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=400',
            averageRating: 4.8,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Tokyo Disney',
            description: 'Magical theme park combining Disney charm with Japanese hospitality and unique attractions',
            category: 'Places',
            imageUrl: 'https://girleatworld.net/wp-content/uploads/2019/05/tokyo-disneyland-08.jpg',
            averageRating: 4.7,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Central Park NYC',
            description: 'Iconic urban park offering green spaces, walking paths, and cultural attractions in Manhattan',
            category: 'Places',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYFg1fhUSFsOpcW70iE11uXzQuTpfj5tv3fA&s',
            averageRating: 4.6,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Spotify',
            description: 'Leading music streaming service with millions of songs, podcasts, and personalized playlists',
            category: 'Apps',
            imageUrl: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=400',
            averageRating: 4.5,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Netflix',
            description: 'Popular streaming platform offering movies, TV shows, and original content',
            category: 'Apps',
            imageUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400',
            averageRating: 4.4,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'ChatGPT',
            description: 'AI-powered conversational assistant that helps with writing, coding, and problem-solving',
            category: 'Apps',
            imageUrl: 'https://thumbs.dreamstime.com/b/chatgpt-artificial-intelligence-program-logo-openai-company-polygonal-green-background-illustration-banner-news-vector-286505082.jpg',
            averageRating: 4.7,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Notion',
            description: 'All-in-one workspace for notes, tasks, wikis, and databases',
            category: 'Apps',
            imageUrl: 'https://preview.redd.it/what-are-your-thoughts-on-notion-ai-has-it-truly-simplified-v0-2telgdckvbmc1.jpg?width=400&format=pjpg&auto=webp&s=ca8fca67ac9c39e086571875be24b2988cf3af5a',
            averageRating: 4.6,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'The Great Gatsby',
            description: 'Classic American novel by F. Scott Fitzgerald exploring themes of wealth, love, and the American Dream',
            category: 'Books',
            imageUrl: 'https://rukminim2.flixcart.com/image/480/640/l4fxh8w0/book/z/0/y/the-great-gatsby-a-novel-original-imagfbmgfsan3gjg.jpeg?q=90',
            averageRating: 4.3,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: '1984',
            description: 'Dystopian masterpiece by George Orwell about totalitarianism and surveillance',
            category: 'Books',
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV4yWihrnwBCaQNXCMF_zSIAPDMidcLtnR3g&s',
            averageRating: 4.7,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Harry Potter and the Sorcerer\'s Stone',
            description: 'Magical adventure story that launched the beloved Harry Potter series by J.K. Rowling',
            category: 'Books',
            imageUrl: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1598823299i/42844155.jpg',
            averageRating: 4.9,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'To Kill a Mockingbird',
            description: 'Pulitzer Prize-winning novel by Harper Lee addressing racial injustice in the American South',
            category: 'Books',
            imageUrl: 'https://m.media-amazon.com/images/I/81gkyAx5-RL._AC_UF1000,1000_QL80_.jpg',
            averageRating: 4.8,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'The Shawshank Redemption',
            description: 'Inspiring drama about hope and friendship in the face of injustice, directed by Frank Darabont',
            category: 'Movies',
            imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400',
            averageRating: 4.9,
            totalReviews: 7,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Inception',
            description: 'Mind-bending sci-fi thriller by Christopher Nolan exploring dreams within dreams',
            category: 'Movies',
            imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400',
            averageRating: 4.8,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Interstellar',
            description: 'Epic space exploration film combining stunning visuals with emotional storytelling',
            category: 'Movies',
            imageUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400',
            averageRating: 4.7,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'The Dark Knight',
            description: 'Groundbreaking superhero film featuring Heath Ledger\'s iconic Joker performance',
            category: 'Movies',
            imageUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400',
            averageRating: 4.9,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Blue Hill',
            description: 'Farm-to-table fine dining restaurant in Manhattan featuring seasonal American cuisine',
            category: 'Restaurants',
            imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
            averageRating: 4.6,
            totalReviews: 3,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Le Bernardin',
            description: 'Legendary French seafood restaurant with three Michelin stars in New York City',
            category: 'Restaurants',
            imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400',
            averageRating: 4.8,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Nobu',
            description: 'Renowned Japanese fusion restaurant known for innovative sushi and elegant atmosphere',
            category: 'Restaurants',
            imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400',
            averageRating: 4.7,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Per Se',
            description: 'Thomas Keller\'s acclaimed New American restaurant offering exceptional tasting menus',
            category: 'Restaurants',
            imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
            averageRating: 4.9,
            totalReviews: 4,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'The Legend of Zelda: Breath of the Wild',
            description: 'Revolutionary open-world adventure game that redefined the Zelda series',
            category: 'Games',
            imageUrl: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=400',
            averageRating: 4.9,
            totalReviews: 7,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Elden Ring',
            description: 'Epic dark fantasy action RPG from FromSoftware with vast open world exploration',
            category: 'Games',
            imageUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=400',
            averageRating: 4.7,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'God of War',
            description: 'Critically acclaimed action-adventure following Kratos and Atreus through Norse mythology',
            category: 'Games',
            imageUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400',
            averageRating: 4.8,
            totalReviews: 5,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            name: 'Red Dead Redemption 2',
            description: 'Immersive Wild West epic with stunning graphics and compelling narrative',
            category: 'Games',
            imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400',
            averageRating: 4.8,
            totalReviews: 6,
            createdAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(items).values(sampleItems);

    console.log('✅ Items seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});