import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        // iPhone 15 Pro (itemId: 1) - 5 reviews - avg: 4.6
        {
            itemId: 1,
            userId: 'user_3',
            rating: 5,
            title: 'Incredible Performance and Camera Quality',
            comment: 'The titanium design feels premium and the camera system is phenomenal. Battery life easily lasts a full day with heavy use. The A17 Pro chip handles everything I throw at it without breaking a sweat.',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            itemId: 1,
            userId: 'user_12',
            rating: 5,
            title: 'Best iPhone Yet',
            comment: 'Upgrading from iPhone 13 Pro was absolutely worth it. The A17 Pro chip is blazing fast and the new action button is incredibly useful. Face ID works flawlessly even in low light.',
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            itemId: 1,
            userId: 'user_28',
            rating: 5,
            title: 'Premium Flagship Experience',
            comment: 'Everything you would expect from Apple. Smooth, reliable, and beautiful design. The 120Hz display is butter smooth and the camera takes stunning photos in any lighting condition.',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            itemId: 1,
            userId: 'user_45',
            rating: 4,
            title: 'Great Phone But Expensive',
            comment: 'Outstanding device in every way, though the price tag is steep for the average consumer. If you can afford it, you won\'t be disappointed with the performance and build quality.',
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            itemId: 1,
            userId: 'user_50',
            rating: 4,
            title: 'Solid Upgrade From Previous Generation',
            comment: 'Noticeable improvements over the previous generation, especially in low-light photography. The USB-C port is a welcome change. Battery optimization could be better with heavy gaming.',
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },

        // MacBook Pro M3 (itemId: 2) - 4 reviews - avg: 4.75
        {
            itemId: 2,
            userId: 'user_7',
            rating: 5,
            title: 'Developer Dream Machine',
            comment: 'Compiles code faster than anything I\'ve used before. The M3 chip is an absolute beast for development work. Battery lasts an entire workday with heavy development tasks running.',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            itemId: 2,
            userId: 'user_19',
            rating: 5,
            title: 'Perfect for Video Editing',
            comment: 'Handles 4K video editing like a champ without breaking a sweat. The Liquid Retina XDR display is stunning. Export times are incredibly fast compared to my old Intel MacBook.',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            itemId: 2,
            userId: 'user_33',
            rating: 5,
            title: 'Best Laptop I\'ve Ever Owned',
            comment: 'The performance is incredible and the laptop stays cool even under heavy load. Battery life is amazing - easily 15+ hours of regular use. Worth every penny.',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            itemId: 2,
            userId: 'user_41',
            rating: 4,
            title: 'Premium But Pricey',
            comment: 'Exceptional build quality and performance but the upgrade options are very expensive. The base model is great but you pay a premium for RAM and storage upgrades.',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },

        // Sony WH-1000XM5 (itemId: 3) - 3 reviews - avg: 4.67
        {
            itemId: 3,
            userId: 'user_5',
            rating: 5,
            title: 'Best Noise Cancelling Headphones',
            comment: 'The noise cancellation is industry-leading. Completely blocks out airplane noise and office chatter. Sound quality is phenomenal with deep bass and clear highs.',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            itemId: 3,
            userId: 'user_22',
            rating: 5,
            title: 'Perfect for Traveling',
            comment: 'Extremely comfortable for long flights and the battery lasts forever. The multipoint connection works flawlessly between my laptop and phone. Worth the investment.',
            createdAt: new Date('2024-03-02').toISOString(),
            updatedAt: new Date('2024-03-02').toISOString(),
        },
        {
            itemId: 3,
            userId: 'user_38',
            rating: 4,
            title: 'Great But Could Use Better Build',
            comment: 'Sound quality and ANC are top-notch but the plastic build feels less premium than the price suggests. Comfort is excellent for extended wear though.',
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },

        // Samsung Galaxy S24 (itemId: 4) - 3 reviews - avg: 4.33
        {
            itemId: 4,
            userId: 'user_9',
            rating: 5,
            title: 'Android Flagship Done Right',
            comment: 'The display is absolutely gorgeous and the camera system rivals the best in the market. Battery optimization is impressive and charging is super fast.',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            itemId: 4,
            userId: 'user_26',
            rating: 4,
            title: 'Solid Upgrade',
            comment: 'Coming from S22, the improvements are noticeable especially in battery life and camera performance. The AI features are interesting but not game-changing.',
            createdAt: new Date('2024-03-06').toISOString(),
            updatedAt: new Date('2024-03-06').toISOString(),
        },
        {
            itemId: 4,
            userId: 'user_44',
            rating: 4,
            title: 'Great Phone, Minor Software Issues',
            comment: 'Hardware is top-notch but experienced a few software bugs that needed updates to fix. Camera takes stunning photos in daylight conditions.',
            createdAt: new Date('2024-03-14').toISOString(),
            updatedAt: new Date('2024-03-14').toISOString(),
        },

        // Grand Canyon (itemId: 5) - 4 reviews - avg: 4.75
        {
            itemId: 5,
            userId: 'user_2',
            rating: 5,
            title: 'Absolutely Breathtaking Natural Wonder',
            comment: 'Pictures don\'t do it justice. The scale and beauty are overwhelming in person. Visited at sunrise and it was one of the most beautiful things I\'ve ever seen.',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            itemId: 5,
            userId: 'user_15',
            rating: 5,
            title: 'Must-See Bucket List Destination',
            comment: 'Hiked down to Plateau Point and the views at every turn were spectacular. Well-maintained trails and informative ranger programs. Plan for at least a full day to truly appreciate it.',
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            itemId: 5,
            userId: 'user_31',
            rating: 5,
            title: 'Incredible Geological Marvel',
            comment: 'The layers of rock tell a story millions of years old. Sunset viewing was magical with the changing colors. The South Rim visitor center has excellent exhibits.',
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            itemId: 5,
            userId: 'user_47',
            rating: 4,
            title: 'Beautiful But Very Crowded',
            comment: 'The canyon itself is stunning but be prepared for crowds, especially at popular viewpoints. Try to visit during shoulder season or weekdays for a better experience.',
            createdAt: new Date('2024-03-16').toISOString(),
            updatedAt: new Date('2024-03-16').toISOString(),
        },

        // Eiffel Tower (itemId: 6) - 5 reviews - avg: 4.8
        {
            itemId: 6,
            userId: 'user_4',
            rating: 5,
            title: 'A Must-See in Paris',
            comment: 'Absolutely breathtaking both during the day and at night when it sparkles. The views from the top are unforgettable. Book tickets in advance online to skip the long lines.',
            createdAt: new Date('2024-02-14').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
        {
            itemId: 6,
            userId: 'user_17',
            rating: 5,
            title: 'Iconic and Beautiful',
            comment: 'Even with the crowds, it\'s worth every minute. The engineering is impressive and the light show at night is magical. The champagne bar at the top adds a special touch.',
            createdAt: new Date('2024-02-24').toISOString(),
            updatedAt: new Date('2024-02-24').toISOString(),
        },
        {
            itemId: 6,
            userId: 'user_29',
            rating: 5,
            title: 'Magical Experience',
            comment: 'Visiting at sunset provided the most amazing views and photos. You can see all of Paris from the top. The surrounding park is perfect for a picnic with a view.',
            createdAt: new Date('2024-03-03').toISOString(),
            updatedAt: new Date('2024-03-03').toISOString(),
        },
        {
            itemId: 6,
            userId: 'user_36',
            rating: 4,
            title: 'Very Crowded But Stunning',
            comment: 'The structure is magnificent but be prepared for long waits and lots of tourists. Security lines can be lengthy. Still an absolute must-see when in Paris.',
            createdAt: new Date('2024-03-11').toISOString(),
            updatedAt: new Date('2024-03-11').toISOString(),
        },
        {
            itemId: 6,
            userId: 'user_49',
            rating: 5,
            title: 'Romantic and Impressive',
            comment: 'Perfect spot for proposals or romantic evenings in the city of lights. The sparkle show on the hour is mesmerizing. Dining at the second floor restaurant was a highlight.',
            createdAt: new Date('2024-03-19').toISOString(),
            updatedAt: new Date('2024-03-19').toISOString(),
        },

        // Tokyo Disney (itemId: 7) - 4 reviews - avg: 4.5
        {
            itemId: 7,
            userId: 'user_8',
            rating: 5,
            title: 'Most Detailed Disney Park',
            comment: 'The attention to detail is incredible. Tokyo DisneySea is unique and beautifully themed. Japanese hospitality makes the experience even more special. Food options are excellent.',
            createdAt: new Date('2024-02-16').toISOString(),
            updatedAt: new Date('2024-02-16').toISOString(),
        },
        {
            itemId: 7,
            userId: 'user_21',
            rating: 5,
            title: 'Exceeded Expectations',
            comment: 'Better than any Disney park I\'ve visited worldwide. The shows are spectacular and rides are well-maintained. Cast members are incredibly helpful even with language barriers.',
            createdAt: new Date('2024-02-27').toISOString(),
            updatedAt: new Date('2024-02-27').toISOString(),
        },
        {
            itemId: 7,
            userId: 'user_35',
            rating: 4,
            title: 'Amazing But Language Barrier',
            comment: 'Absolutely magical experience with some of the best theming I\'ve seen. Some shows and attractions are only in Japanese which can be challenging. Still highly recommend.',
            createdAt: new Date('2024-03-07').toISOString(),
            updatedAt: new Date('2024-03-07').toISOString(),
        },
        {
            itemId: 7,
            userId: 'user_42',
            rating: 4,
            title: 'Great Park, Plan Ahead',
            comment: 'Wonderful attractions and very clean facilities. Can get extremely crowded, especially on weekends. FastPass system helps but arrive early for popular rides.',
            createdAt: new Date('2024-03-13').toISOString(),
            updatedAt: new Date('2024-03-13').toISOString(),
        },

        // Central Park NYC (itemId: 8) - 3 reviews - avg: 4.67
        {
            itemId: 8,
            userId: 'user_11',
            rating: 5,
            title: 'Urban Oasis in Manhattan',
            comment: 'A perfect escape from the city chaos. Beautiful in every season with endless walking paths and activities. The Bethesda Fountain and Bow Bridge are must-see spots.',
            createdAt: new Date('2024-02-19').toISOString(),
            updatedAt: new Date('2024-02-19').toISOString(),
        },
        {
            itemId: 8,
            userId: 'user_27',
            rating: 5,
            title: 'Perfect for Every Season',
            comment: 'Visited in fall and the foliage was spectacular. Great for jogging, picnics, or just relaxing. The variety of landscapes and landmarks keeps it interesting.',
            createdAt: new Date('2024-03-04').toISOString(),
            updatedAt: new Date('2024-03-04').toISOString(),
        },
        {
            itemId: 8,
            userId: 'user_39',
            rating: 4,
            title: 'Beautiful But Can Be Crowded',
            comment: 'Lovely green space in the heart of the city. Some areas get very crowded, especially on weekends. Early morning visits offer a more peaceful experience.',
            createdAt: new Date('2024-03-17').toISOString(),
            updatedAt: new Date('2024-03-17').toISOString(),
        },

        // Spotify (itemId: 9) - 5 reviews - avg: 4.6
        {
            itemId: 9,
            userId: 'user_1',
            rating: 5,
            title: 'Best Music Streaming Service',
            comment: 'The algorithm recommendations are spot-on and I discover new music constantly. Huge library with excellent audio quality on premium. The collaborative playlists are a great feature.',
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            itemId: 9,
            userId: 'user_14',
            rating: 5,
            title: 'Incredible Music Discovery',
            comment: 'Discover Weekly and Release Radar consistently introduce me to artists I love. The podcast selection is also impressive. Cross-device syncing works flawlessly.',
            createdAt: new Date('2024-02-21').toISOString(),
            updatedAt: new Date('2024-02-21').toISOString(),
        },
        {
            itemId: 9,
            userId: 'user_23',
            rating: 5,
            title: 'Worth Every Penny',
            comment: 'Premium subscription is absolutely worth it for the ad-free experience and offline downloads. The curated playlists for every mood are perfect.',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            itemId: 9,
            userId: 'user_34',
            rating: 4,
            title: 'Great Service With Minor Issues',
            comment: 'Love the music selection and features but occasionally have connectivity issues. The free tier has too many ads but premium fixes that.',
            createdAt: new Date('2024-03-09').toISOString(),
            updatedAt: new Date('2024-03-09').toISOString(),
        },
        {
            itemId: 9,
            userId: 'user_46',
            rating: 4,
            title: 'Good But Could Improve Artist Payments',
            comment: 'Excellent user experience and music library. Wish they paid artists better per stream. The Spotify Wrapped annual summary is always fun.',
            createdAt: new Date('2024-03-16').toISOString(),
            updatedAt: new Date('2024-03-16').toISOString(),
        },

        // Netflix (itemId: 10) - 4 reviews - avg: 4.25
        {
            itemId: 10,
            userId: 'user_6',
            rating: 5,
            title: 'Still the Best Streaming Platform',
            comment: 'Massive content library with excellent original series. The recommendation algorithm is accurate and the interface is user-friendly across all devices.',
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        {
            itemId: 10,
            userId: 'user_18',
            rating: 4,
            title: 'Great Content But Expensive',
            comment: 'Quality original shows and movies but the price keeps going up. The download feature for offline viewing is convenient for travel.',
            createdAt: new Date('2024-02-26').toISOString(),
            updatedAt: new Date('2024-02-26').toISOString(),
        },
        {
            itemId: 10,
            userId: 'user_30',
            rating: 4,
            title: 'Good Selection, Occasional Misses',
            comment: 'Lots of quality content but some shows get canceled too early. 4K streaming looks fantastic when available. The profiles feature works well for families.',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            itemId: 10,
            userId: 'user_43',
            rating: 4,
            title: 'Solid Platform With Room to Improve',
            comment: 'Reliable streaming with mostly good content. Would like to see more classic films in the library. The password sharing crackdown is frustrating.',
            createdAt: new Date('2024-03-14').toISOString(),
            updatedAt: new Date('2024-03-14').toISOString(),
        },

        // ChatGPT (itemId: 11) - 6 reviews - avg: 4.67
        {
            itemId: 11,
            userId: 'user_10',
            rating: 5,
            title: 'Revolutionary AI Assistant',
            comment: 'Incredible tool for research, writing, and problem-solving. The responses are detailed and contextually aware. Has dramatically improved my productivity.',
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            itemId: 11,
            userId: 'user_16',
            rating: 5,
            title: 'Game Changer for Productivity',
            comment: 'Use it daily for coding help, writing assistance, and brainstorming. The Plus subscription with GPT-4 is worth every penny. Amazingly helpful for learning new topics.',
            createdAt: new Date('2024-02-23').toISOString(),
            updatedAt: new Date('2024-02-23').toISOString(),
        },
        {
            itemId: 11,
            userId: 'user_24',
            rating: 5,
            title: 'Impressive AI Capabilities',
            comment: 'The natural language understanding is remarkable. Great for debugging code, explaining complex concepts, and drafting emails. The vision capabilities in GPT-4 are fantastic.',
            createdAt: new Date('2024-03-02').toISOString(),
            updatedAt: new Date('2024-03-02').toISOString(),
        },
        {
            itemId: 11,
            userId: 'user_32',
            rating: 5,
            title: 'Indispensable Tool',
            comment: 'Has become an essential part of my workflow. Excellent for research, creative writing, and technical questions. The conversation memory feature is very useful.',
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            itemId: 11,
            userId: 'user_40',
            rating: 4,
            title: 'Very Useful But Has Limitations',
            comment: 'Incredibly helpful for most tasks but can occasionally provide inaccurate information. Always verify important details. The custom GPTs feature is innovative.',
            createdAt: new Date('2024-03-13').toISOString(),
            updatedAt: new Date('2024-03-13').toISOString(),
        },
        {
            itemId: 11,
            userId: 'user_48',
            rating: 4,
            title: 'Powerful AI With Room to Grow',
            comment: 'Amazing technology that\'s improving rapidly. Sometimes struggles with very recent information. The API integration possibilities are exciting for developers.',
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },

        // Notion (itemId: 12) - 4 reviews - avg: 4.5
        {
            itemId: 12,
            userId: 'user_13',
            rating: 5,
            title: 'All-in-One Workspace Solution',
            comment: 'Replaced multiple apps with Notion for notes, tasks, and databases. The flexibility is unmatched. Slight learning curve but worth it for the productivity gains.',
            createdAt: new Date('2024-02-17').toISOString(),
            updatedAt: new Date('2024-02-17').toISOString(),
        },
        {
            itemId: 12,
            userId: 'user_25',
            rating: 5,
            title: 'Perfect for Personal and Team Use',
            comment: 'Excellent collaboration features and the template gallery is incredibly helpful. Use it for everything from meeting notes to project management. The AI features are a nice addition.',
            createdAt: new Date('2024-02-29').toISOString(),
            updatedAt: new Date('2024-02-29').toISOString(),
        },
        {
            itemId: 12,
            userId: 'user_37',
            rating: 4,
            title: 'Powerful But Can Be Overwhelming',
            comment: 'So many features it takes time to master. Once you get the hang of it, it\'s incredibly versatile. Mobile app could use some improvements.',
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            itemId: 12,
            userId: 'user_45',
            rating: 4,
            title: 'Great Tool With Minor Performance Issues',
            comment: 'Love the customization options and database features. Occasionally experiences lag with large workspaces. The free tier is generous for personal use.',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },

        // The Great Gatsby (itemId: 13) - 3 reviews - avg: 4.33
        {
            itemId: 13,
            userId: 'user_20',
            rating: 5,
            title: 'Timeless American Classic',
            comment: 'Fitzgerald\'s prose is absolutely beautiful. The themes of wealth, love, and the American Dream remain relevant today. Every re-read reveals new layers of meaning.',
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            itemId: 13,
            userId: 'user_28',
            rating: 4,
            title: 'Beautiful Writing, Complex Characters',
            comment: 'The symbolism and imagery are masterful. Some readers might find it slow-paced but the character development is worth the patience. A true literary masterpiece.',
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            itemId: 13,
            userId: 'user_41',
            rating: 4,
            title: 'Quintessential Jazz Age Novel',
            comment: 'Captures the essence of the 1920s perfectly. The tragic story and vivid descriptions make it unforgettable. Required reading for understanding American literature.',
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },

        // 1984 (itemId: 14) - 5 reviews - avg: 4.6
        {
            itemId: 14,
            userId: 'user_3',
            rating: 5,
            title: 'Chillingly Prophetic Masterpiece',
            comment: 'Orwell\'s dystopian vision feels more relevant than ever. The concepts of surveillance and thought control are disturbingly prescient. A must-read for everyone.',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            itemId: 14,
            userId: 'user_19',
            rating: 5,
            title: 'Terrifyingly Relevant Today',
            comment: 'The parallels to modern surveillance society are striking. Powerful warning about totalitarianism and the manipulation of truth. Uncomfortable but essential reading.',
            createdAt: new Date('2024-02-24').toISOString(),
            updatedAt: new Date('2024-02-24').toISOString(),
        },
        {
            itemId: 14,
            userId: 'user_31',
            rating: 5,
            title: 'Haunting and Thought-Provoking',
            comment: 'One of the most important books ever written. The concepts of doublethink and newspeak are brilliantly conceived. Stays with you long after finishing.',
            createdAt: new Date('2024-03-06').toISOString(),
            updatedAt: new Date('2024-03-06').toISOString(),
        },
        {
            itemId: 14,
            userId: 'user_44',
            rating: 4,
            title: 'Dark But Essential Reading',
            comment: 'Heavy subject matter but incredibly well-written. The bleak ending is hard to process but drives home the message. Everyone should read this at least once.',
            createdAt: new Date('2024-03-14').toISOString(),
            updatedAt: new Date('2024-03-14').toISOString(),
        },
        {
            itemId: 14,
            userId: 'user_50',
            rating: 4,
            title: 'Powerful Warning About Power',
            comment: 'Brilliant exploration of authoritarianism and control. Some sections can be slow but the overall impact is profound. The world-building is meticulous.',
            createdAt: new Date('2024-03-19').toISOString(),
            updatedAt: new Date('2024-03-19').toISOString(),
        },

        // Harry Potter (itemId: 15) - 6 reviews - avg: 4.83
        {
            itemId: 15,
            userId: 'user_7',
            rating: 5,
            title: 'Magical Series That Defines a Generation',
            comment: 'Rowling created an entire world that feels real and lived-in. The character development across seven books is remarkable. Perfect for all ages despite being marketed to children.',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            itemId: 15,
            userId: 'user_22',
            rating: 5,
            title: 'Timeless Fantasy Classic',
            comment: 'The world-building is extraordinary and the themes of friendship, courage, and sacrifice resonate deeply. Each book gets darker and more complex. Absolutely captivating.',
            createdAt: new Date('2024-02-26').toISOString(),
            updatedAt: new Date('2024-02-26').toISOString(),
        },
        {
            itemId: 15,
            userId: 'user_33',
            rating: 5,
            title: 'Perfect Blend of Magic and Reality',
            comment: 'The way magic is woven into a relatable coming-of-age story is brilliant. The characters feel like old friends. Re-reading as an adult reveals even more depth.',
            createdAt: new Date('2024-03-04').toISOString(),
            updatedAt: new Date('2024-03-04').toISOString(),
        },
        {
            itemId: 15,
            userId: 'user_42',
            rating: 5,
            title: 'Enchanting Adventure Series',
            comment: 'Impossibly creative and endlessly entertaining. The plot twists are masterfully executed and the emotional payoff is worth the investment. A true phenomenon for good reason.',
            createdAt: new Date('2024-03-11').toISOString(),
            updatedAt: new Date('2024-03-11').toISOString(),
        },
        {
            itemId: 15,
            userId: 'user_49',
            rating: 5,
            title: 'Grew Up With These Books',
            comment: 'Reading these as they were released was a magical experience. The series matured along with its readers. The detail and foreshadowing throughout is incredible.',
            createdAt: new Date('2024-03-17').toISOString(),
            updatedAt: new Date('2024-03-17').toISOString(),
        },
        {
            itemId: 15,
            userId: 'user_15',
            rating: 5,
            title: 'Ultimate Fantasy Epic',
            comment: 'Everything you want in a fantasy series - magic, adventure, friendship, and epic battles. The emotional depth in the later books is surprising and powerful.',
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },

        // To Kill a Mockingbird (itemId: 16) - 4 reviews - avg: 4.75
        {
            itemId: 16,
            userId: 'user_9',
            rating: 5,
            title: 'Profound Examination of Justice',
            comment: 'Lee\'s masterpiece tackles racism and morality with grace and power. Atticus Finch is one of literature\'s greatest heroes. Essential reading for understanding American society.',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            itemId: 16,
            userId: 'user_26',
            rating: 5,
            title: 'Beautiful and Heartbreaking',
            comment: 'Scout\'s perspective gives the story both innocence and wisdom. The courtroom scenes are powerful and the lessons about empathy are timeless. Incredible character development.',
            createdAt: new Date('2024-02-27').toISOString(),
            updatedAt: new Date('2024-02-27').toISOString(),
        },
        {
            itemId: 16,
            userId: 'user_38',
            rating: 5,
            title: 'Literary Perfection',
            comment: 'Every element works together flawlessly. The social commentary is as relevant today as when it was written. Harper Lee created something truly special.',
            createdAt: new Date('2024-03-09').toISOString(),
            updatedAt: new Date('2024-03-09').toISOString(),
        },
        {
            itemId: 16,
            userId: 'user_47',
            rating: 4,
            title: 'Important and Moving Novel',
            comment: 'Powerful exploration of prejudice and moral courage. Some aspects feel dated but the core message remains vital. The childhood nostalgia mixed with harsh reality is effective.',
            createdAt: new Date('2024-03-16').toISOString(),
            updatedAt: new Date('2024-03-16').toISOString(),
        },

        // Shawshank Redemption (itemId: 17) - 7 reviews - avg: 4.71
        {
            itemId: 17,
            userId: 'user_1',
            rating: 5,
            title: 'Perfect Film in Every Way',
            comment: 'One of the greatest movies ever made. The story of hope and friendship is beautifully told. Morgan Freeman and Tim Robbins give career-defining performances.',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            itemId: 17,
            userId: 'user_14',
            rating: 5,
            title: 'Timeless Masterpiece',
            comment: 'Every viewing reveals new details. The ending is incredibly satisfying and earned. The themes of hope and perseverance resonate powerfully. Absolutely flawless filmmaking.',
            createdAt: new Date('2024-02-21').toISOString(),
            updatedAt: new Date('2024-02-21').toISOString(),
        },
        {
            itemId: 17,
            userId: 'user_23',
            rating: 5,
            title: 'The Ultimate Feel-Good Drama',
            comment: 'Despite the prison setting, this is ultimately an uplifting story. The character development is exceptional and the pacing is perfect. A film that stays with you.',
            createdAt: new Date('2024-02-29').toISOString(),
            updatedAt: new Date('2024-02-29').toISOString(),
        },
        {
            itemId: 17,
            userId: 'user_34',
            rating: 5,
            title: 'Brilliantly Crafted Story',
            comment: 'The narration, acting, and cinematography all come together perfectly. One of those rare films that improves with each viewing. Deservedly considered one of the best.',
            createdAt: new Date('2024-03-07').toISOString(),
            updatedAt: new Date('2024-03-07').toISOString(),
        },
        {
            itemId: 17,
            userId: 'user_43',
            rating: 5,
            title: 'Hope in the Darkest Places',
            comment: 'The message about never giving up hope is powerful and moving. Red and Andy\'s friendship is beautifully portrayed. The score enhances every emotional moment.',
            createdAt: new Date('2024-03-13').toISOString(),
            updatedAt: new Date('2024-03-13').toISOString(),
        },
        {
            itemId: 17,
            userId: 'user_50',
            rating: 4,
            title: 'Near-Perfect Prison Drama',
            comment: 'Exceptional storytelling with incredible performances. Slightly slow in the middle but the payoff is worth it. One of the most emotionally satisfying endings in cinema.',
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },
        {
            itemId: 17,
            userId: 'user_5',
            rating: 4,
            title: 'Inspiring and Well-Executed',
            comment: 'Beautiful adaptation of Stephen King\'s novella. The themes of institutional corruption and personal redemption are handled expertly. Highly rewatchable.',
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },

        // Inception (itemId: 18) - 6 reviews - avg: 4.5
        {
            itemId: 18,
            userId: 'user_2',
            rating: 5,
            title: 'Mind-Bending Masterpiece',
            comment: 'Nolan\'s most complex and rewarding film. The dream-within-dream concept is executed brilliantly. Requires multiple viewings to catch all the details. Absolutely stunning.',
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            itemId: 18,
            userId: 'user_17',
            rating: 5,
            title: 'Original and Thrilling',
            comment: 'One of the most creative sci-fi films ever made. The action sequences are incredible and the emotional core is strong. Hans Zimmer\'s score is iconic.',
            createdAt: new Date('2024-02-23').toISOString(),
            updatedAt: new Date('2024-02-23').toISOString(),
        },
        {
            itemId: 18,
            userId: 'user_29',
            rating: 5,
            title: 'Visually Stunning Thriller',
            comment: 'The practical effects are incredible and the rotating hallway fight is legendary. The ending leaves you thinking. Perfect blend of action and intellectual stimulation.',
            createdAt: new Date('2024-03-03').toISOString(),
            updatedAt: new Date('2024-03-03').toISOString(),
        },
        {
            itemId: 18,
            userId: 'user_36',
            rating: 4,
            title: 'Complex But Rewarding',
            comment: 'Requires full attention but pays off tremendously. Some plot points need explanation but the overall experience is amazing. The cast ensemble is perfect.',
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            itemId: 18,
            userId: 'user_45',
            rating: 4,
            title: 'Ambitious and Entertaining',
            comment: 'Nolan pushes the boundaries of blockbuster filmmaking. Can be confusing on first watch but that adds to the rewatch value. The heist structure works perfectly.',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            itemId: 18,
            userId: 'user_48',
            rating: 4,
            title: 'Intellectually Stimulating Spectacle',
            comment: 'Balances big-budget action with philosophical questions about reality. The ensemble cast delivers strong performances. That spinning top ending is perfect.',
            createdAt: new Date('2024-03-19').toISOString(),
            updatedAt: new Date('2024-03-19').toISOString(),
        },

        // Interstellar (itemId: 19) - 5 reviews - avg: 4.6
        {
            itemId: 19,
            userId: 'user_4',
            rating: 5,
            title: 'Epic Space Adventure',
            comment: 'Visually breathtaking with a powerful emotional core about love and sacrifice. The science is mostly accurate and fascinating. The docking scene is one of cinema\'s best.',
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        {
            itemId: 19,
            userId: 'user_21',
            rating: 5,
            title: 'Beautiful and Profound',
            comment: 'The blend of hard science and human emotion is masterful. Matthew McConaughey gives an incredible performance. The tesseract scene is mind-blowing and moving.',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            itemId: 19,
            userId: 'user_30',
            rating: 5,
            title: 'Stunning Achievement',
            comment: 'Nolan\'s most ambitious film succeeds on every level. The practical effects and IMAX cinematography are spectacular. Hans Zimmer\'s score is hauntingly beautiful.',
            createdAt: new Date('2024-03-04').toISOString(),
            updatedAt: new Date('2024-03-04').toISOString(),
        },
        {
            itemId: 19,
            userId: 'user_39',
            rating: 4,
            title: 'Ambitious Space Epic',
            comment: 'The visuals and concepts are incredible though some plot elements stretch credibility. The emotional impact is powerful. The time dilation scenes are heartbreaking.',
            createdAt: new Date('2024-03-11').toISOString(),
            updatedAt: new Date('2024-03-11').toISOString(),
        },
        {
            itemId: 19,
            userId: 'user_46',
            rating: 4,
            title: 'Visually Spectacular Drama',
            comment: 'The black hole visualization is scientifically accurate and stunning. Some dialogue is hard to hear but the story is compelling. Best experienced on the biggest screen possible.',
            createdAt: new Date('2024-03-17').toISOString(),
            updatedAt: new Date('2024-03-17').toISOString(),
        },

        // The Dark Knight (itemId: 20) - 6 reviews - avg: 4.83
        {
            itemId: 20,
            userId: 'user_6',
            rating: 5,
            title: 'Best Superhero Film Ever Made',
            comment: 'Heath Ledger\'s Joker is one of the greatest villain performances in cinema history. Transcends the superhero genre to become a crime epic. Perfectly paced and executed.',
            createdAt: new Date('2024-02-14').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
        {
            itemId: 20,
            userId: 'user_18',
            rating: 5,
            title: 'Masterclass in Filmmaking',
            comment: 'Every element works perfectly - acting, directing, score, cinematography. The moral dilemmas make it more than just an action film. Ledger\'s Oscar was well-deserved.',
            createdAt: new Date('2024-02-24').toISOString(),
            updatedAt: new Date('2024-02-24').toISOString(),
        },
        {
            itemId: 20,
            userId: 'user_27',
            rating: 5,
            title: 'Revolutionized Comic Book Movies',
            comment: 'Set a new standard for the genre with its darker, more realistic approach. The action sequences are incredible and the story is genuinely gripping. A modern classic.',
            createdAt: new Date('2024-03-02').toISOString(),
            updatedAt: new Date('2024-03-02').toISOString(),
        },
        {
            itemId: 20,
            userId: 'user_35',
            rating: 5,
            title: 'Perfect Blend of Action and Drama',
            comment: 'Nolan elevated Batman to new heights. The ferry scene is one of the most tense sequences ever filmed. Every actor brings their A-game. Timeless entertainment.',
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            itemId: 20,
            userId: 'user_42',
            rating: 5,
            title: 'Iconic Villain Performance',
            comment: 'Heath Ledger completely disappeared into the role of the Joker. The bank heist opening is legendary. A superhero film with the depth of a serious crime drama.',
            createdAt: new Date('2024-03-14').toISOString(),
            updatedAt: new Date('2024-03-14').toISOString(),
        },
        {
            itemId: 20,
            userId: 'user_49',
            rating: 5,
            title: 'Defining Superhero Epic',
            comment: 'Proves that comic book movies can be both entertaining and thought-provoking. The chaos versus order theme is expertly explored. Infinitely rewatchable.',
            createdAt: new Date('2024-03-19').toISOString(),
            updatedAt: new Date('2024-03-19').toISOString(),
        },

        // Blue Hill (itemId: 21) - 3 reviews - avg: 4.67
        {
            itemId: 21,
            userId: 'user_8',
            rating: 5,
            title: 'Farm-to-Table Excellence',
            comment: 'Incredible dining experience with ingredients sourced from their own farm. Each course tells a story of the land and seasons. Service is impeccable and knowledgeable.',
            createdAt: new Date('2024-02-16').toISOString(),
            updatedAt: new Date('2024-02-16').toISOString(),
        },
        {
            itemId: 21,
            userId: 'user_24',
            rating: 5,
            title: 'Unforgettable Culinary Journey',
            comment: 'The tasting menu showcases the best of New York ingredients. Every dish is beautifully presented and bursting with flavor. Worth every penny for a special occasion.',
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            itemId: 21,
            userId: 'user_40',
            rating: 4,
            title: 'Outstanding But Expensive',
            comment: 'The quality is undeniable but the prices reflect that. The attention to detail in every course is remarkable. Reservations are extremely hard to get.',
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },

        // Le Bernardin (itemId: 22) - 4 reviews - avg: 4.75
        {
            itemId: 22,
            userId: 'user_11',
            rating: 5,
            title: 'Seafood Perfection',
            comment: 'The freshest fish prepared with French technique and precision. Eric Ripert\'s vision is executed flawlessly. The service is formal but warm. A true three-star Michelin experience.',
            createdAt: new Date('2024-02-17').toISOString(),
            updatedAt: new Date('2024-02-17').toISOString(),
        },
        {
            itemId: 22,
            userId: 'user_25',
            rating: 5,
            title: 'World-Class Dining',
            comment: 'Every dish is a work of art. The tuna carpaccio is legendary and for good reason. Wine pairings are expertly chosen. Maintains its stellar reputation year after year.',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            itemId: 22,
            userId: 'user_37',
            rating: 5,
            title: 'Exceptional French Cuisine',
            comment: 'The consistency and quality are remarkable. Each course is perfectly balanced and the flavors are subtle yet profound. The dining room ambiance is elegant without being stuffy.',
            createdAt: new Date('2024-03-09').toISOString(),
            updatedAt: new Date('2024-03-09').toISOString(),
        },
        {
            itemId: 22,
            userId: 'user_44',
            rating: 4,
            title: 'Refined Seafood Experience',
            comment: 'Top-tier seafood preparation with impeccable service. The prices are high but reflect the quality. The desserts are also outstanding. A bucket list restaurant.',
            createdAt: new Date('2024-03-16').toISOString(),
            updatedAt: new Date('2024-03-16').toISOString(),
        },

        // Nobu (itemId: 23) - 5 reviews - avg: 4.4
        {
            itemId: 23,
            userId: 'user_3',
            rating: 5,
            title: 'Innovative Japanese-Peruvian Fusion',
            comment: 'The black cod with miso is legendary and lives up to the hype. Creative cocktails and an extensive sake list. The atmosphere is sophisticated and energetic.',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            itemId: 23,
            userId: 'user_19',
            rating: 5,
            title: 'Consistently Excellent',
            comment: 'The quality across multiple locations is impressive. Sushi is incredibly fresh and the hot dishes are full of flavor. Service is attentive and efficient.',
            createdAt: new Date('2024-02-26').toISOString(),
            updatedAt: new Date('2024-02-26').toISOString(),
        },
        {
            itemId: 23,
            userId: 'user_31',
            rating: 4,
            title: 'Great Food, Trendy Scene',
            comment: 'The food is outstanding but can be noisy and crowded. The yellowtail jalapeño is a must-try. Reservations are essential and prices are on the higher side.',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            itemId: 23,
            userId: 'user_41',
            rating: 4,
            title: 'Upscale Japanese Dining',
            comment: 'The signature dishes are excellent though some items feel overpriced. The rock shrimp tempura is delicious. Good for business dinners or special occasions.',
            createdAt: new Date('2024-03-13').toISOString(),
            updatedAt: new Date('2024-03-13').toISOString(),
        },
        {
            itemId: 23,
            userId: 'user_47',
            rating: 4,
            title: 'Solid Choice for Japanese',
            comment: 'High quality ingredients and creative preparations. The ambiance can be a bit loud for intimate conversations. Overall a reliable choice for upscale Japanese cuisine.',
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },

        // Per Se (itemId: 24) - 4 reviews - avg: 4.75
        {
            itemId: 24,
            userId: 'user_12',
            rating: 5,
            title: 'Thomas Keller\'s Masterpiece',
            comment: 'An unforgettable dining experience from start to finish. Nine courses of pure excellence with flawless execution. The view of Central Park adds to the magic.',
            createdAt: new Date('2024-02-19').toISOString(),
            updatedAt: new Date('2024-02-19').toISOString(),
        },
        {
            itemId: 24,
            userId: 'user_28',
            rating: 5,
            title: 'Pinnacle of Fine Dining',
            comment: 'Every detail is considered, from the amuse-bouche to the mignardises. The oysters and pearls is iconic. Service is choreographed to perfection. Expensive but worth it.',
            createdAt: new Date('2024-03-03').toISOString(),
            updatedAt: new Date('2024-03-03').toISOString(),
        },
        {
            itemId: 24,
            userId: 'user_38',
            rating: 5,
            title: 'Culinary Excellence',
            comment: 'Thomas Keller\'s dedication to perfection shines through in every course. The wine pairings are exceptional. A meal to remember for a lifetime.',
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            itemId: 24,
            userId: 'user_46',
            rating: 4,
            title: 'Exceptional But Very Formal',
            comment: 'The food is incredible but the formal atmosphere might feel stiff to some. The attention to detail is remarkable. Book well in advance for this bucket list experience.',
            createdAt: new Date('2024-03-17').toISOString(),
            updatedAt: new Date('2024-03-17').toISOString(),
        },

        // Zelda BOTW (itemId: 25) - 7 reviews - avg: 4.71
        {
            itemId: 25,
            userId: 'user_10',
            rating: 5,
            title: 'Revolutionized Open World Gaming',
            comment: 'The freedom to explore and solve puzzles in multiple ways is incredible. The physics engine allows for creative solutions. Every corner of Hyrule has something interesting to discover.',
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-09').toISOString(),
        },
        {
            itemId: 25,
            userId: 'user_16',
            rating: 5,
            title: 'Perfect Game Design',
            comment: 'The sense of adventure and discovery is unmatched. Combat is satisfying and the shrines provide great puzzles. The art style is timeless and beautiful.',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            itemId: 25,
            userId: 'user_32',
            rating: 5,
            title: 'Masterpiece of Gaming',
            comment: 'Every system works together perfectly to create an immersive world. The climbing mechanic alone changes everything. Hundreds of hours of content without feeling padded.',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            itemId: 25,
            userId: 'user_40',
            rating: 5,
            title: 'Best Zelda Game',
            comment: 'Takes everything great about Zelda and reimagines it for modern gaming. The divine beasts are epic and the memories system adds emotional depth. Absolutely essential.',
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            itemId: 25,
            userId: 'user_45',
            rating: 5,
            title: 'Incredible Open World',
            comment: 'The attention to detail is astounding. Weather effects, wildlife behavior, and NPC schedules make the world feel alive. The soundtrack is subtle but perfect.',
            createdAt: new Date('2024-03-14').toISOString(),
            updatedAt: new Date('2024-03-14').toISOString(),
        },
        {
            itemId: 25,
            userId: 'user_48',
            rating: 4,
            title: 'Amazing But Weapon Durability Annoying',
            comment: 'Nearly perfect game but the weapon breaking system can be frustrating. Everything else from exploration to combat is outstanding. Easily 100+ hours of content.',
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },
        {
            itemId: 25,
            userId: 'user_13',
            rating: 4,
            title: 'Excellent Adventure',
            comment: 'The freedom and exploration are fantastic. Dungeons are shorter than traditional Zelda but the shrines make up for it. A must-play for any gamer.',
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },

        // Elden Ring (itemId: 26) - 6 reviews - avg: 4.67
        {
            itemId: 26,
            userId: 'user_7',
            rating: 5,
            title: 'FromSoftware\'s Magnum Opus',
            comment: 'The open world design breathes new life into the Souls formula. Boss fights are epic and challenging. The lore and world-building are deep and mysterious.',
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        {
            itemId: 26,
            userId: 'user_20',
            rating: 5,
            title: 'Masterful Game Design',
            comment: 'The combination of Dark Souls combat with open world exploration works perfectly. Build variety is incredible. George R.R. Martin\'s contribution to the lore shows.',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            itemId: 26,
            userId: 'user-33',
            rating: 5,
            title: 'Challenging and Rewarding',
            comment: 'The difficulty is tough but fair. Exploration is constantly rewarding with new weapons and spells. The legacy dungeons are brilliantly designed. A true achievement.',
            createdAt: new Date('2024-03-04').toISOString(),
            updatedAt: new Date('2024-03-04').toISOString(),
        },
        {
            itemId: 26,
            userId: 'user_39',
            rating: 5,
            title: 'Incredible Fantasy Epic',
            comment: 'The world is massive and filled with secrets. Boss variety is impressive and each feels unique. The art direction and atmosphere are phenomenal.',
            createdAt: new Date('2024-03-11').toISOString(),
            updatedAt: new Date('2024-03-11').toISOString(),
        },
        {
            itemId: 26,
            userId: 'user_44',
            rating: 4,
            title: 'Great But Unforgiving',
            comment: 'Amazing game but the difficulty might turn off some players. The open world can make progression confusing. Once it clicks though, it\'s incredibly satisfying.',
            createdAt: new Date('2024-03-16').toISOString(),
            updatedAt: new Date('2024-03-16').toISOString(),
        },
        {
            itemId: 26,
            userId: 'user_50',
            rating: 4,
            title: 'Excellent Dark Fantasy',
            comment: 'The scope is ambitious and mostly succeeds. Some late-game areas feel rushed. The character customization and build options are fantastic.',
            createdAt: new Date('2024-03-19').toISOString(),
            updatedAt: new Date('2024-03-19').toISOString(),
        },

        // God of War (itemId: 27) - 5 reviews - avg: 4.8
        {
            itemId: 27,
            userId: 'user_5',
            rating: 5,
            title: 'Emotional and Epic',
            comment: 'The father-son relationship between Kratos and Atreus is beautifully developed. Combat is visceral and satisfying. The one-shot camera technique is incredible.',
            createdAt: new Date('2024-02-14').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
        {
            itemId: 27,
            userId: 'user_18',
            rating: 5,
            title: 'Perfect Reboot',
            comment: 'Reinvents the series while staying true to its roots. The Norse mythology setting is fascinating. Boss fights are memorable and challenging. A masterclass in storytelling.',
            createdAt: new Date('2024-02-26').toISOString(),
            updatedAt: new Date('2024-02-26').toISOString(),
        },
        {
            itemId: 27,
            userId: 'user_30',
            rating: 5,
            title: 'Stunning Achievement',
            comment: 'Every aspect from graphics to gameplay to story is polished to perfection. The Leviathan Axe is one of gaming\'s best weapons. Mimir\'s stories add depth to the world.',
            createdAt: new Date('2024-03-06').toISOString(),
            updatedAt: new Date('2024-03-06').toISOString(),
        },
        {
            itemId: 27,
            userId: 'user_42',
            rating: 5,
            title: 'Incredible Action Adventure',
            comment: 'The maturity in the storytelling is refreshing. Kratos\' character development is remarkable. The realms are beautifully designed and fun to explore.',
            createdAt: new Date('2024-03-13').toISOString(),
            updatedAt: new Date('2024-03-13').toISOString(),
        },
        {
            itemId: 27,
            userId: 'user_49',
            rating: 4,
            title: 'Near-Perfect Game',
            comment: 'Absolutely stunning game with minor pacing issues in the middle. The ending is powerful and sets up the sequel perfectly. Combat can feel repetitive occasionally.',
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },

        // Red Dead Redemption 2 (itemId: 28) - 6 reviews - avg: 4.67
        {
            itemId: 28,
            userId: 'user_1',
            rating: 5,
            title: 'Most Detailed Open World Ever',
            comment: 'The attention to detail is staggering. Every NPC has a routine and the world feels truly alive. Arthur Morgan is one of gaming\'s best protagonists. A masterpiece.',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            itemId: 28,
            userId: 'user_14',
            rating: 5,
            title: 'Epic Western Tale',
            comment: 'The story of the Van der Linde gang is tragic and compelling. The graphics are stunning and the soundtrack is perfect. Hunting and fishing are surprisingly deep.',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            itemId: 28,
            userId: 'user_27',
            rating: 5,
            title: 'Rockstar\'s Finest Work',
            comment: 'Every system is polished and the world is incredibly immersive. The camp interactions add so much depth. Random encounters make exploration rewarding.',
            createdAt: new Date('2024-03-02').toISOString(),
            updatedAt: new Date('2024-03-02').toISOString(),
        },
        {
            itemId: 28,
            userId: 'user_36',
            rating: 5,
            title: 'Beautiful and Emotional',
            comment: 'The epilogue ties everything together perfectly. Graphics are photorealistic in places. The honor system affects the story in meaningful ways. Unforgettable experience.',
            createdAt: new Date('2024-03-09').toISOString(),
            updatedAt: new Date('2024-03-09').toISOString(),
        },
        {
            itemId: 28,
            userId: 'user_43',
            rating: 4,
            title: 'Amazing But Slow-Paced',
            comment: 'Incredible attention to detail but the realism can make it feel slow at times. The story is fantastic once it picks up. Controls take getting used to.',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            itemId: 28,
            userId: 'user_47',
            rating: 4,
            title: 'Gorgeous Western Epic',
            comment: 'The world is beautiful and the characters are well-developed. Some missions feel repetitive. The ending is emotionally powerful. A technical marvel.',
            createdAt: new Date('2024-03-17').toISOString(),
            updatedAt: new Date('2024-03-17').toISOString(),
        },
    ];

    await db.insert(reviews).values(sampleReviews);

    console.log('✅ Reviews seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});